sudo: false

language: python
python:
 - 2.7

addons:
  apt:
    sources:
      - libsdl1.2debian
      - libfdt1
      - libpixman-1-0

before_install:
 - chmod +x ./travis/install
 - pip install virtualenv

install: ./travis/install

before_script:
 - chmod +x ./travis/build
script: ./travis/build

env:
  global:
    - PEBBLE_TOOL=4.2
